/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MyprojectsPimage from './MyprojectsPimage';

/**
 * The Myprojects model module.
 * @module model/Myprojects
 * @version 1.0.0
 */
class Myprojects {
    /**
     * Constructs a new <code>Myprojects</code>.
     * @alias module:model/Myprojects
     * @param pimage {module:model/MyprojectsPimage} 
     * @param ptitle {String} 
     * @param pstart {String} 
     * @param pend {String} 
     * @param pduration {String} 
     * @param pabstract {String} 
     * @param pdescription {String} 
     * @param pga {String} 
     * @param pwebsite {String} 
     */
    constructor(pimage, ptitle, pstart, pend, pduration, pabstract, pdescription, pga, pwebsite) { 
        
        Myprojects.initialize(this, pimage, ptitle, pstart, pend, pduration, pabstract, pdescription, pga, pwebsite);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pimage, ptitle, pstart, pend, pduration, pabstract, pdescription, pga, pwebsite) { 
        obj['pimage'] = pimage;
        obj['ptitle'] = ptitle;
        obj['pstart'] = pstart;
        obj['pend'] = pend;
        obj['pduration'] = pduration;
        obj['pabstract'] = pabstract;
        obj['pdescription'] = pdescription;
        obj['pga'] = pga;
        obj['pwebsite'] = pwebsite;
    }

    /**
     * Constructs a <code>Myprojects</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Myprojects} obj Optional instance to populate.
     * @return {module:model/Myprojects} The populated <code>Myprojects</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Myprojects();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('pimage')) {
                obj['pimage'] = MyprojectsPimage.constructFromObject(data['pimage']);
            }
            if (data.hasOwnProperty('ptitle')) {
                obj['ptitle'] = ApiClient.convertToType(data['ptitle'], 'String');
            }
            if (data.hasOwnProperty('pstart')) {
                obj['pstart'] = ApiClient.convertToType(data['pstart'], 'String');
            }
            if (data.hasOwnProperty('pend')) {
                obj['pend'] = ApiClient.convertToType(data['pend'], 'String');
            }
            if (data.hasOwnProperty('pduration')) {
                obj['pduration'] = ApiClient.convertToType(data['pduration'], 'String');
            }
            if (data.hasOwnProperty('pabstract')) {
                obj['pabstract'] = ApiClient.convertToType(data['pabstract'], 'String');
            }
            if (data.hasOwnProperty('pdescription')) {
                obj['pdescription'] = ApiClient.convertToType(data['pdescription'], 'String');
            }
            if (data.hasOwnProperty('pga')) {
                obj['pga'] = ApiClient.convertToType(data['pga'], 'String');
            }
            if (data.hasOwnProperty('pwebsite')) {
                obj['pwebsite'] = ApiClient.convertToType(data['pwebsite'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Myprojects.prototype['_id'] = undefined;

/**
 * @member {module:model/MyprojectsPimage} pimage
 */
Myprojects.prototype['pimage'] = undefined;

/**
 * @member {String} ptitle
 */
Myprojects.prototype['ptitle'] = undefined;

/**
 * @member {String} pstart
 */
Myprojects.prototype['pstart'] = undefined;

/**
 * @member {String} pend
 */
Myprojects.prototype['pend'] = undefined;

/**
 * @member {String} pduration
 */
Myprojects.prototype['pduration'] = undefined;

/**
 * @member {String} pabstract
 */
Myprojects.prototype['pabstract'] = undefined;

/**
 * @member {String} pdescription
 */
Myprojects.prototype['pdescription'] = undefined;

/**
 * @member {String} pga
 */
Myprojects.prototype['pga'] = undefined;

/**
 * @member {String} pwebsite
 */
Myprojects.prototype['pwebsite'] = undefined;






export default Myprojects;

