/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tasks model module.
 * @module model/Tasks
 * @version 1.0.0
 */
class Tasks {
    /**
     * Constructs a new <code>Tasks</code>.
     * @alias module:model/Tasks
     * @param tname {String} 
     * @param sdate {Number} 
     * @param edate {Number} 
     * @param vpms {Number} 
     * @param tdescription {String} 
     */
    constructor(tname, sdate, edate, vpms, tdescription) { 
        
        Tasks.initialize(this, tname, sdate, edate, vpms, tdescription);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tname, sdate, edate, vpms, tdescription) { 
        obj['tname'] = tname;
        obj['sdate'] = sdate;
        obj['edate'] = edate;
        obj['vpms'] = vpms;
        obj['tdescription'] = tdescription;
    }

    /**
     * Constructs a <code>Tasks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tasks} obj Optional instance to populate.
     * @return {module:model/Tasks} The populated <code>Tasks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tasks();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('tname')) {
                obj['tname'] = ApiClient.convertToType(data['tname'], 'String');
            }
            if (data.hasOwnProperty('sdate')) {
                obj['sdate'] = ApiClient.convertToType(data['sdate'], 'Number');
            }
            if (data.hasOwnProperty('edate')) {
                obj['edate'] = ApiClient.convertToType(data['edate'], 'Number');
            }
            if (data.hasOwnProperty('vpms')) {
                obj['vpms'] = ApiClient.convertToType(data['vpms'], 'Number');
            }
            if (data.hasOwnProperty('tdescription')) {
                obj['tdescription'] = ApiClient.convertToType(data['tdescription'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Tasks.prototype['_id'] = undefined;

/**
 * @member {String} tname
 */
Tasks.prototype['tname'] = undefined;

/**
 * @member {Number} sdate
 */
Tasks.prototype['sdate'] = undefined;

/**
 * @member {Number} edate
 */
Tasks.prototype['edate'] = undefined;

/**
 * @member {Number} vpms
 */
Tasks.prototype['vpms'] = undefined;

/**
 * @member {String} tdescription
 */
Tasks.prototype['tdescription'] = undefined;






export default Tasks;

