/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.Myprojects();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Myprojects', function() {
    it('should create an instance of Myprojects', function() {
      // uncomment below and update the code to test Myprojects
      //var instane = new TempApi.Myprojects();
      //expect(instance).to.be.a(TempApi.Myprojects);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pimage (base name: "pimage")', function() {
      // uncomment below and update the code to test the property pimage
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property ptitle (base name: "ptitle")', function() {
      // uncomment below and update the code to test the property ptitle
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pstart (base name: "pstart")', function() {
      // uncomment below and update the code to test the property pstart
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pend (base name: "pend")', function() {
      // uncomment below and update the code to test the property pend
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pduration (base name: "pduration")', function() {
      // uncomment below and update the code to test the property pduration
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pabstract (base name: "pabstract")', function() {
      // uncomment below and update the code to test the property pabstract
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pdescription (base name: "pdescription")', function() {
      // uncomment below and update the code to test the property pdescription
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pga (base name: "pga")', function() {
      // uncomment below and update the code to test the property pga
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

    it('should have the property pwebsite (base name: "pwebsite")', function() {
      // uncomment below and update the code to test the property pwebsite
      //var instance = new TempApi.Myprojects();
      //expect(instance).to.be();
    });

  });

}));
